### ISSUE TITLE
大神，首页信息刷不出来是不是把接口关了

### ISSUE THREAD

**Issue by qdstar** [johnnyzhang1992/gushi_lite#1]
appservice?t=1555759372051:2725 GET https://xuegushi.cn/wxxcx/getTopics?user_id=undefined&openId=undefined&wx_token= 500 (Internal Server Error)

**Comment by johnnyzhang1992** [comment]
> appservice?t=1555759372051:2725 GET https://xuegushi.cn/wxxcx/getTopics?user_id=undefined&openId=undefined&wx_token= 500 (Internal Server Error)

这个接口在首页用不到，在发现页用的到，现在主要放节气列表。

原来这个topic接口需要 user_id和 wx_token 字段，就是需要用户登陆。

好像对未登录用户确实不够友好。

已经去掉限制了。感谢提醒。
