### ISSUE TITLE
为什么我点哪里都是加载失败呢，需要怎么做？

### ISSUE THREAD

**Issue by DwnTT** [johnnyzhang1992/gushi_lite#3]

**Comment by johnnyzhang1992** [comment]
报啥错呢？截个图。

如果所有请求都报错，那么需要再开发工具里面去掉现在域名的设置。

post请求，报错收藏等，需要登录（绑定置顶的小程序appid，配合后端解密

**Comment by DwnTT** [comment]
![NQ(90U6GNS1_6Z92X 26_FL](https://user-images.githubusercontent.com/95964424/220505490-d6b06afd-edd0-4692-8c94-937304dcd56c.png)
![HAT~ML0G 8ADDJND2EHHY8C](https://user-images.githubusercontent.com/95964424/220505531-036900f4-854b-4ffb-bd93-6a4d7e009eda.png)
![G 4I8Z`VBU6Q{MA2KUSWGQ3](https://user-images.githubusercontent.com/95964424/220505548-7902eae6-2f10-4836-aac9-91d75d3c8c09.png)
![KER%W{(N% J~6KJI R N4%6](https://user-images.githubusercontent.com/95964424/220505557-b8f2a341-74c2-4bb3-a55d-9b2561cccae2.png)
就我把你的压缩包解压之后打开就都是这样的

**Comment by johnnyzhang1992** [comment]
<img width="414" alt="image" src="https://user-images.githubusercontent.com/9986068/220505832-a8c02a05-c3dd-4cee-bfa4-3f92acaa5337.png">
把这个勾打上。。。

**Comment by DwnTT** [comment]
大佬，很多都解决了。那个我想问一下，这个古诗这么多是怎么出现的呢，我也没有找到数据库什么的


Everglow
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "johnnyzhang1992/gushi_lite"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月22日(星期三) 上午10:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [johnnyzhang1992/gushi_lite] 为什么我点哪里都是加载失败呢，需要怎么做？ (Issue #3)





 

 把这个勾打上。。。

**Comment by johnnyzhang1992** [comment]
> 大佬，很多都解决了。那个我想问一下，这个古诗这么多是怎么出现的呢，我也没有找到数据库什么的 Everglow ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "johnnyzhang1992/gushi_lite" ***@***.***&gt;; 发送时间:&nbsp;2023年2月22日(星期三) 上午10:31 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [johnnyzhang1992/gushi_lite] 为什么我点哪里都是加载失败呢，需要怎么做？ (Issue #3) 把这个勾打上。。。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

看API请求哇，数据肯定不会无缘无故的就来了。

**Comment by DwnTT** [comment]
刚学没几天 ，不太看得懂， ***@***.***都是在请求数据吗





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "johnnyzhang1992/gushi_lite"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月22日(星期三) 上午10:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [johnnyzhang1992/gushi_lite] 为什么我点哪里都是加载失败呢，需要怎么做？ (Issue #3)





  
大佬，很多都解决了。那个我想问一下，这个古诗这么多是怎么出现的呢，我也没有找到数据库什么的 Everglow @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "johnnyzhang1992/gushi_lite" @.&gt;; 发送时间:&nbsp;2023年2月22日(星期三) 上午10:31 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [johnnyzhang1992/gushi_lite] 为什么我点哪里都是加载失败呢，需要怎么做？ (Issue #3) 把这个勾打上。。。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
看API请求哇，数据肯定不会无缘无故的就来了。

**Comment by DwnTT** [comment]
我能把你的稍微改改用来当毕业设计吗？


Everglow
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "johnnyzhang1992/gushi_lite"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月22日(星期三) 上午10:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [johnnyzhang1992/gushi_lite] 为什么我点哪里都是加载失败呢，需要怎么做？ (Issue #3)





  
大佬，很多都解决了。那个我想问一下，这个古诗这么多是怎么出现的呢，我也没有找到数据库什么的 Everglow @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "johnnyzhang1992/gushi_lite" @.&gt;; 发送时间:&nbsp;2023年2月22日(星期三) 上午10:31 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [johnnyzhang1992/gushi_lite] 为什么我点哪里都是加载失败呢，需要怎么做？ (Issue #3) 把这个勾打上。。。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
看API请求哇，数据肯定不会无缘无故的就来了。

**Comment by johnnyzhang1992** [comment]
> 

东西是开源的，出了问题和我无关呦(*╹▽╹*)

**Comment by DwnTT** [comment]
你这个好复杂哦，有点不适合我，我等级太低了，我就想做一个搜索功能，能查找数据库就好了


Everglow
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "johnnyzhang1992/gushi_lite"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月22日(星期三) 中午11:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [johnnyzhang1992/gushi_lite] 为什么我点哪里都是加载失败呢，需要怎么做？ (Issue #3)





   
东西是开源的，出了问题和我无关呦(╹▽╹)

**Comment by johnnyzhang1992** [comment]
done
